### ISSUE TITLE
0.4 扫描直接退出

### ISSUE THREAD

**Issue by zhzyker** [zhzyker/vulmap#13]
于 2020-12-15 10:35:00 修复更新 0.4

**Comment by safebaseline** [comment]
![image](https://user-images.githubusercontent.com/38883009/103529137-15b80180-4ec0-11eb-914b-69374fae4192.png)
0.4直接退出！

**Comment by zhzyker** [comment]
在一楼的时间之前下载的程序存在该问题

**Comment by zhzyker** [comment]
0.5中全部解决 @safebaseline
