### ISSUE TITLE
big code

### ISSUE THREAD

**Issue by Martin2877** [zhzyker/vulmap#14]
oh man,  your  code so big

**Comment by zhzyker** [comment]
emmm

**Comment by Martin2877** [comment]
a ba a ba a ba

**Comment by zhzyker** [comment]
什么加密对话... ... 
暂时不考虑拆分~

**Comment by channelchan22** [comment]
+1

**Comment by zhzyker** [comment]
0.6 开始 vulmap 改为模块化，不再把所有代码放在一个文件，欢迎批评改造~
***
Starting from 0.6, vulmap has been changed to modular, welcome to modify
@Martin2877 @channelchan22
