### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by horseworkbench** [zhzyker/vulmap#16]
希望协议支持https,在使用过程中发现-u 后地址为https则会直接退出检测

**Comment by zhzyker** [comment]
vulmap从0.1版本开始就是支持https协议扫描的
关于0.4版本扫描退出的问题参考 [https://github.com/zhzyker/vulmap/issues/13](https://github.com/zhzyker/vulmap/issues/13)

**Comment by horseworkbench** [comment]
可能是我在网址后面加入了错误的目录，比如 www.example.com/login.php 导致识别问题

**Comment by zhzyker** [comment]
我测试没有发现该问题
提供一下截图？
