### ISSUE TITLE
NameError: name 'AF_INET' is not defined

### ISSUE THREAD

**Issue by z3dc0ps** [zhzyker/vulmap#19]
![1](https://user-images.githubusercontent.com/61974788/103976773-ad0da500-519d-11eb-961e-2db50413e44b.PNG)

**Comment by mcblog** [comment]
the same problem

**Comment by zhzyker** [comment]
```
pip3 install -U --force-reinstall --no-binary :all: gevent
```
https://github.com/python-greenlet/greenlet/issues/178  的解决方法

**Comment by zhzyker** [comment]
```
pip3 install -U --force-reinstall --no-binary :all: gevent
```
https://github.com/gevent/gevent/issues/1260  Temporary solution:
@mcblog @z3dc0ps

**Comment by zhzyker** [comment]
I need to provide ```pip3 freeze``` to analyze this problem
