### ISSUE TITLE
aspx网站扫描出struts2漏洞

### ISSUE THREAD

**Issue by fishgoudan** [zhzyker/vulmap#25]
扫描一个aspx的网站的时候，查出来3个struts2的漏洞，是正常的吗

**Comment by zhzyker** [comment]
不正常，我去修误报，如果有更多信息更好

**Comment by fishgoudan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "之乎者也"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 晚上7:58
收件人: "zhzyker/vulmap"<vulmap@noreply.github.com&gt;; 
抄送: "rainbow~🌈"<673444340@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [zhzyker/vulmap] aspx网站扫描出struts2漏洞 (#25)





 
不正常，我去修误报，如果有更多信息更好

**Comment by zhzyker** [comment]
0.6 中处理了多种误报
@fishgoudan
