### ISSUE TITLE
0.6版本运行报错

### ISSUE THREAD

**Issue by jhwxj** [zhzyker/vulmap#28]
![图片](https://user-images.githubusercontent.com/55729404/106440398-c90e1900-64b3-11eb-87d6-de21387af9d4.png)

**Comment by jhwxj** [comment]
>python vulmap.py
                   __
                  [  |
  _   __  __   _   | |  _ .--..--.   ,--.  _ .--.
 [ \ [  ][  | | |  | | [ `.-. .-. | `'_\ :[ '/'`\ \
  \ \/ /  | \_/ |, | |  | | | | | | // | |,| \__/ |
   \__/   '.__.'_/[___][___||__||__]'-;__/| ;.___/
                                          [__|
Traceback (most recent call last):
  File "vulmap.py", line 90, in <module>
    version_check()  # 检查vulmap版本
  File "F:\tools\vulmap-main\module\allcheck.py", line 22, in version_check
    print(now.timed(de=0) + color.yew_info() + color.yellow(" Currently the latest version: " + version))
AttributeError: 'Colored' object has no attribute 'yew_info'

**Comment by zhzyker** [comment]
发现了，我憨憨把yel_info写成了yew_info

**Comment by zhzyker** [comment]
update了

**Comment by jhwxj** [comment]
谢谢表哥
