### ISSUE TITLE
dnslog问题，以及最近ceye.io不明原因爆炸

### ISSUE THREAD

**Issue by zhzyker** [zhzyker/vulmap#32]
最近的ceye.io爆炸导致无法通过dns检测，导致例如fastjson等均无法检测
计划引入更多的dnslog平台例如dnslog.cn
各位师傅也可推荐一些稳定开放的dns平台

**Comment by cr1bug** [comment]
> 最近的ceye.io爆炸导致无法通过dns检测，导致例如fastjson等均无法检测
> 计划引入更多的dnslog平台例如dnslog.cn
> 各位师傅也可推荐一些稳定开放的dns平台

http://www.0kdns.net
http://www.0kns.net
http://dnsbin.zhack.ca
http://s0x.cn
http://burpcollaborator.net

**Comment by zhzyker** [comment]
已采纳，整入0.7
