### ISSUE TITLE
建议提供一个新功能 让fofa扫的时候可以检测指定的类型漏洞

### ISSUE THREAD

**Issue by 1151806933** [zhzyker/vulmap#41]
![图片](https://user-images.githubusercontent.com/61936554/113163376-b1b09980-9272-11eb-9020-5041262a73cb.png)

**Comment by zhzyker** [comment]
-a 选项允许指定webapps  
例如` -a shiro`
具体支持哪些webapps参考`--help` 或者`readme.md`
